import "./globals.css";
import NavBar from "./components/navbar";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`pt-12`}
      >
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
