import "./globals.css";
import NavBar from "./components/navbar";
import { Providers } from "./providers";
import { getServerSession } from "next-auth"

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={`bg-black`}
      >
         <Providers session={session}>
        <NavBar/>
        {children}
        </Providers>
      </body>
    </html>
  );
}
