import "./globals.css";
import NavBar from "./components/navbar";
import { Providers } from "./providers";
import { getServerSession } from "next-auth"
import { ClerkProvider } from '@clerk/nextjs';
import { ptBR } from "@clerk/localizations"; 

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <ClerkProvider
    signInUrl="/sign-in"
    signUpUrl="/sign-up"
    afterSignInUrl="/leader"
    localization={ptBR}

    >
    <html lang="pt-BR">
      <body
        className={`bg-black text-white `}
      >
         <Providers session={session}>
         
        <NavBar/>
        {children}
       
        </Providers>
      </body>
    </html>
     </ClerkProvider>
  );
}
